//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace callback.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExitOnUserLogoff
        {
            get
            {
                return ((bool)(this["ExitOnUserLogoff"]));
            }
            set
            {
                this["ExitOnUserLogoff"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExitOnSkypeStop
        {
            get
            {
                return ((bool)(this["ExitOnSkypeStop"]));
            }
            set
            {
                this["ExitOnSkypeStop"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetSilentModeOn
        {
            get
            {
                return ((bool)(this["SetSilentModeOn"]));
            }
            set
            {
                this["SetSilentModeOn"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAPIErrorMessages
        {
            get
            {
                return ((bool)(this["ShowAPIErrorMessages"]));
            }
            set
            {
                this["ShowAPIErrorMessages"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartSkypeIfNeeded
        {
            get
            {
                return ((bool)(this["StartSkypeIfNeeded"]));
            }
            set
            {
                this["StartSkypeIfNeeded"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartSkypeMinimized
        {
            get
            {
                return ((bool)(this["StartSkypeMinimized"]));
            }
            set
            {
                this["StartSkypeMinimized"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartSkypeNosplash
        {
            get
            {
                return ((bool)(this["StartSkypeNosplash"]));
            }
            set
            {
                this["StartSkypeNosplash"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoScroll
        {
            get
            {
                return ((bool)(this["AutoScroll"]));
            }
            set
            {
                this["AutoScroll"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideAPI
        {
            get
            {
                return ((bool)(this["HideAPI"]));
            }
            set
            {
                this["HideAPI"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTime
        {
            get
            {
                return ((bool)(this["FirstTime"]));
            }
            set
            {
                this["FirstTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysFirstTime
        {
            get
            {
                return ((bool)(this["AlwaysFirstTime"]));
            }
            set
            {
                this["AlwaysFirstTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlwaysNonWaitedAttach
        {
            get
            {
                return ((bool)(this["AlwaysNonWaitedAttach"]));
            }
            set
            {
                this["AlwaysNonWaitedAttach"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDebugOn
        {
            get
            {
                return ((bool)(this["AutoDebugOn"]));
            }
            set
            {
                this["AutoDebugOn"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Blocking
        {
            get
            {
                return ((bool)(this["Blocking"]));
            }
            set
            {
                this["Blocking"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CommandId
        {
            get
            {
                return ((bool)(this["CommandId"]));
            }
            set
            {
                this["CommandId"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveTheText
        {
            get
            {
                return ((bool)(this["SaveTheText"]));
            }
            set
            {
                this["SaveTheText"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedCommandText
        {
            get
            {
                return ((string)(this["SavedCommandText"]));
            }
            set
            {
                this["SavedCommandText"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedExpectedText
        {
            get
            {
                return ((string)(this["SavedExpectedText"]));
            }
            set
            {
                this["SavedExpectedText"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RetryCommandTimeOut
        {
            get
            {
                return ((bool)(this["RetryCommandTimeOut"]));
            }
            set
            {
                this["RetryCommandTimeOut"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideSkype4COM
        {
            get
            {
                return ((bool)(this["HideSkype4COM"]));
            }
            set
            {
                this["HideSkype4COM"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_StartUsTotallyInvisible
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_StartUsTotallyInvisible"]));
            }
            set
            {
                this["TheNotifyIconExample_StartUsTotallyInvisible"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TheNotifyIconExample_ShowSystemTrayNotifyIcon
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_ShowSystemTrayNotifyIcon"]));
            }
            set
            {
                this["TheNotifyIconExample_ShowSystemTrayNotifyIcon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_StartUsMinimized
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_StartUsMinimized"]));
            }
            set
            {
                this["TheNotifyIconExample_StartUsMinimized"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_ShowUsInTaskbarWhenMinimized
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_ShowUsInTaskbarWhenMinimized"]));
            }
            set
            {
                this["TheNotifyIconExample_ShowUsInTaskbarWhenMinimized"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TheNotifyIconExample_ShowUsInTaskbarWhenNormal
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_ShowUsInTaskbarWhenNormal"]));
            }
            set
            {
                this["TheNotifyIconExample_ShowUsInTaskbarWhenNormal"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_ExitAlways
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_ExitAlways"]));
            }
            set
            {
                this["TheNotifyIconExample_ExitAlways"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_ExitWarningMessageBoxIsDisplayed
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_ExitWarningMessageBoxIsDisplayed"]));
            }
            set
            {
                this["TheNotifyIconExample_ExitWarningMessageBoxIsDisplayed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_NotifyIconMouseSingleRightClickDisabled
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_NotifyIconMouseSingleRightClickDisabled"]));
            }
            set
            {
                this["TheNotifyIconExample_NotifyIconMouseSingleRightClickDisabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TheNotifyIconExample_NotifyIconMouseSingleLeftClickShowsForm1
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_NotifyIconMouseSingleLeftClickShowsForm1"]));
            }
            set
            {
                this["TheNotifyIconExample_NotifyIconMouseSingleLeftClickShowsForm1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_NotifyIconMouseSingleRightClickShowsForm1
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_NotifyIconMouseSingleRightClickShowsForm1"]));
            }
            set
            {
                this["TheNotifyIconExample_NotifyIconMouseSingleRightClickShowsForm1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_NotifyIconMouseSingleLeftClickShowsContextMenuStrip
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_NotifyIconMouseSingleLeftClickShowsContextMenuStrip"]));
            }
            set
            {
                this["TheNotifyIconExample_NotifyIconMouseSingleLeftClickShowsContextMenuStrip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_NotifyIconMouseSingleLeftClickUsesDifferentContextMenuStrip
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_NotifyIconMouseSingleLeftClickUsesDifferentContextMenuStrip"]));
            }
            set
            {
                this["TheNotifyIconExample_NotifyIconMouseSingleLeftClickUsesDifferentContextMenuStrip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_NotifyIconMouseDoubleLeftClickShowsContextMenuStrip
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_NotifyIconMouseDoubleLeftClickShowsContextMenuStrip"]));
            }
            set
            {
                this["TheNotifyIconExample_NotifyIconMouseDoubleLeftClickShowsContextMenuStrip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_NotifyIconMouseDoubleRightClickShowsContextMenuStrip
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_NotifyIconMouseDoubleRightClickShowsContextMenuStrip"]));
            }
            set
            {
                this["TheNotifyIconExample_NotifyIconMouseDoubleRightClickShowsContextMenuStrip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_NotifyIconMouseDoubleLeftClickShowsForm1
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_NotifyIconMouseDoubleLeftClickShowsForm1"]));
            }
            set
            {
                this["TheNotifyIconExample_NotifyIconMouseDoubleLeftClickShowsForm1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_NotifyIconMouseDoubleRightClickShowsForm1
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_NotifyIconMouseDoubleRightClickShowsForm1"]));
            }
            set
            {
                this["TheNotifyIconExample_NotifyIconMouseDoubleRightClickShowsForm1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TheNotifyIconExample_ExitWarningBalloonTipIsDisplayed
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_ExitWarningBalloonTipIsDisplayed"]));
            }
            set
            {
                this["TheNotifyIconExample_ExitWarningBalloonTipIsDisplayed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int TheNotifyIconExample_ExitWarningBalloonTipIsDisplayedForThisManyMilliseconds
        {
            get
            {
                return ((int)(this["TheNotifyIconExample_ExitWarningBalloonTipIsDisplayedForThisManyMilliseconds"]));
            }
            set
            {
                this["TheNotifyIconExample_ExitWarningBalloonTipIsDisplayedForThisManyMilliseconds"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TheNotifyIconExample_Form1MouseDoubleLeftClickMinimizesForm1
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_Form1MouseDoubleLeftClickMinimizesForm1"]));
            }
            set
            {
                this["TheNotifyIconExample_Form1MouseDoubleLeftClickMinimizesForm1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_Form1MouseDoubleLeftClickShowsContextMenuStrip
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_Form1MouseDoubleLeftClickShowsContextMenuStrip"]));
            }
            set
            {
                this["TheNotifyIconExample_Form1MouseDoubleLeftClickShowsContextMenuStrip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_Form1MouseDoubleRightClickMinimizesForm1
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_Form1MouseDoubleRightClickMinimizesForm1"]));
            }
            set
            {
                this["TheNotifyIconExample_Form1MouseDoubleRightClickMinimizesForm1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_Form1MouseDoubleRightClickShowsContextMenuStrip
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_Form1MouseDoubleRightClickShowsContextMenuStrip"]));
            }
            set
            {
                this["TheNotifyIconExample_Form1MouseDoubleRightClickShowsContextMenuStrip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_Form1MouseSingleLeftClickMinimizesForm1
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_Form1MouseSingleLeftClickMinimizesForm1"]));
            }
            set
            {
                this["TheNotifyIconExample_Form1MouseSingleLeftClickMinimizesForm1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_Form1MouseSingleLeftClickShowsContextMenuStrip
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_Form1MouseSingleLeftClickShowsContextMenuStrip"]));
            }
            set
            {
                this["TheNotifyIconExample_Form1MouseSingleLeftClickShowsContextMenuStrip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_Form1MouseSingleLeftClickUsesDifferentContextMenuStrip
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_Form1MouseSingleLeftClickUsesDifferentContextMenuStrip"]));
            }
            set
            {
                this["TheNotifyIconExample_Form1MouseSingleLeftClickUsesDifferentContextMenuStrip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_Form1MouseSingleRightClickDisabled
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_Form1MouseSingleRightClickDisabled"]));
            }
            set
            {
                this["TheNotifyIconExample_Form1MouseSingleRightClickDisabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_Form1MouseSingleRightClickMinimizesForm1
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_Form1MouseSingleRightClickMinimizesForm1"]));
            }
            set
            {
                this["TheNotifyIconExample_Form1MouseSingleRightClickMinimizesForm1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheNotifyIconExample_StartUsSingleInstanceOnly
        {
            get
            {
                return ((bool)(this["TheNotifyIconExample_StartUsSingleInstanceOnly"]));
            }
            set
            {
                this["TheNotifyIconExample_StartUsSingleInstanceOnly"] = value;
            }
        }
    }
}
